$(document).ready(function(){
    $("#clickable").click(function(){
        $("#design").show();
        $("#hide").toggle();
    });
})
$(document).ready(function(){
    $("#clickable2").click(function(){
        $("#develop").show();
        $("#hide2").toggle();
    });
});
$(document).ready(function(){
    $("#clickable3").click(function(){
        $("#product").show();
        $("#hide3").toggle();
    });
});